// Generated by Wrangler on Wed May 22 2024 16:14:51 GMT+0100 (Western European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  METADATA_CACHE: KVNamespace;
  NEXT_PUBLIC_ETH_NODE: 'https://ethereum-rpc.publicnode.com';
  NEXT_PUBLIC_SUBGRAPH_URL: 'https://graph-node-tmp.dogswithnodes.com/subgraphs/name/eigen-next';
}
